package org.fit.proxy.jdbc;

import java.sql.SQLException;
import java.sql.Statement;

/**
 * 
 * @author Ondřej Marek
 */
public class ProxyTools {
	
	public static String getAutoGeneratedKeysDescription(int autoGeneratedKeys) throws SQLException {
		StringBuilder sb = new StringBuilder();
		
		switch (autoGeneratedKeys) {
		case Statement.NO_GENERATED_KEYS : sb.append("NO_GENERATED_KEYS"); break;
		case Statement.RETURN_GENERATED_KEYS : sb.append("RETURN_GENERATED_KEYS"); break;
		default: throw new SQLException(sb.append("Execute update: invalid autoGeneratedKeys constant : ").append(autoGeneratedKeys).toString());
		}
		
		sb.append('(').append(autoGeneratedKeys).append(')');
		
		return sb.toString();
	}
}
